# deployment.yaml

# --- 1. The Deployment: Manages the running instances (pods) of your application ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-api-deployment
spec:
  replicas: 1 # Start with a single instance
  selector:
    matchLabels:
      app: iris-api
  template:
    metadata:
      labels:
        app: iris-api
    spec:
      containers:
      - name: iris-api-container
        image: IMAGE_PLACEHOLDER # This is replaced by your CD pipeline
        ports:
        - containerPort: 8000
        # --- ✅ ADD THIS ENTIRE BLOCK ---
        # This tells GKE Autopilot how much CPU and Memory to give your pod.
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
        # --- END OF ADDED BLOCK ---

---
# --- 2. The Service: Creates a stable network endpoint (IP address) for our API ---
apiVersion: v1
kind: Service
metadata:
  name: iris-api-service
spec:
  type: LoadBalancer 
  selector:
    app: iris-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000