# GitHub Actions Workflow: Continuous Deployment for Iris API
#
# This workflow automates the process of building a Docker image for the Iris API,
# pushing it to Docker Hub, and deploying it to a Google Kubernetes Engine (GKE) cluster.
# It triggers automatically on every push to the 'main' branch.

name: Continuous Deployment - Deploy Iris API to Kubernetes

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # --- 1. Checkout Code ---
      # Checks out the repository code. This now includes the pre-trained model.joblib.
      - name: Checkout repository
        uses: actions/checkout@v3

      # --- 2. Docker Build & Push ---
      # This section logs into Docker Hub, builds the Docker image, and pushes it.
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Tags the image with the Git commit SHA for version tracking.
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iris-api:${{ github.sha }}

      # --- 3. GCP Authentication & GKE Setup ---
      # Installs the gcloud CLI and authenticates with your Google Cloud project to deploy to GKE.
      - name: Install gcloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          export_default_credentials: false
      
      - name: Install gke-gcloud-auth-plugin
        run: gcloud components install gke-gcloud-auth-plugin

      - name: Authenticate gcloud with service account
        uses: 'google-github-actions/auth@v2'
        with: 
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Configures kubectl to connect to your GKE cluster.
      - name: Get GKE credentials
        run: |
          gcloud config set project velvety-rookery-461404-b5
          gcloud container clusters get-credentials iris-cluster --zone us-central1 --project velvety-rookery-461404-b5

      # --- 4. Deploy to Kubernetes ---
      # Deploys the application to the GKE cluster.
      - name: Deploy to Kubernetes cluster
        run: |
          sed -i 's|IMAGE_PLACEHOLDER|${{ secrets.DOCKERHUB_USERNAME }}/iris-api:${{ github.sha }}|g' deployment.yaml
          kubectl apply --validate=false -f deployment.yaml
          kubectl rollout status deployment/iris-api-deployment

      # --- 5. Post-deployment Comment (using CML) ---
      - name: Set up Node.js for CML
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install CML via NPM
        run: npm install -g @dvcorg/cml

      - name: Post deployment status as a comment on the merge commit
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "✅ **Deployment Successful**\n\nA new version of the Iris API has been deployed to Kubernetes.\n\n📦 **Image Tag:** \`${{ secrets.DOCKERHUB_USERNAME }}/iris-api:${{ github.sha }}\`" > cml-comment.md
          cml comment create cml-comment.md --commit-sha=${{ github.sha }}
