name: Continuous Deployment - Deploy Iris API to Kubernetes

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # --- Checkout Code ---
      - name: Checkout repository
        uses: actions/checkout@v3

      # --- Docker Build & Push ---
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iris-api:${{ github.sha }}

      # --- Install gcloud CLI & auth plugin ---
      - name: Install gcloud SDK and GKE auth plugin
        run: |
          sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | \
            sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | \
            sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk google-cloud-sdk-gke-gcloud-auth-plugin

      # --- Authenticate with GCP ---
      - name: Authenticate gcloud with service account
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > sa-key.json
          gcloud auth activate-service-account --key-file=sa-key.json
          gcloud config set project velvety-rookery-461404-b5
          gcloud container clusters get-credentials iris-cluster --zone us-central1-a

      # --- Deploy to Kubernetes ---
      - name: Deploy to Kubernetes cluster
        run: |
          sed -i 's|IMAGE_PLACEHOLDER|${{ secrets.DOCKERHUB_USERNAME }}/iris-api:${{ github.sha }}|g' deployment.yaml
          kubectl apply -f deployment.yaml
          kubectl rollout status deployment/iris-api-deployment

      # --- Post-deployment Comment (CML) ---
      - name: Set up Node.js for CML
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install CML via NPM
        run: npm install -g @dvcorg/cml

      - name: Post deployment status as a comment on the merge commit
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create --commit-sha=${{ github.sha }} "✅ **Deployment Successful**\n\nA new version of the Iris API has been deployed to Kubernetes.\n* **Image Tag:** `${{ secrets.DOCKERHUB_USERNAME }}/iris-api:${{ github.sha }}`"
